<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ModuleFieldSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('module_fields')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $htmlTemplate = <<<'HTML'
<p><strong>DENR ADMINISTRATIVE ORDER</strong></p><p>No. 2026-__________</p><p><strong>SUBJECT</strong>       <strong>:</strong>\t<strong>DECLARING CERTAIN PORTION OF FORESTLAND IN BARANGAY CANTUGAS AS CRITICAL HABITAT FOR <em>Rafflesia mixta</em> AND OTHER THREATENED WILDLIFE SPECIES COVERING AN AREA OF 159.73 HECTARES LOCATED IN THE MUNICIPALITY OF MAINIT, PROVINCE OF SURIGAO DEL NORTE</strong></p><p><strong><br></strong>           Pursuant to Section 25 of Republic Act (RA) No. 9147, otherwise known as the ΓÇ£Wildlife Resources Conservation and Protection ActΓÇ¥, Rules 25.1-25.5 of the Joint DENR-DA-PCSD Administrative Order No. 01, Series of 2004 or the joint Implementing Rules and Regulations (IRR) of R.A. 9147, and consistent with the DENR Memorandum Circular (DMC) No. 2 of 2007 or the ΓÇ£Guidelines on the Establishment and Management of Critical HabitatΓÇ¥, certain parcel of land of the public domain situated in Brgy. Cantugas, Municipality of Mainit, Province of Surigao del Norte, is hereby declared as Critical Habitat and shall be known as the <em>ΓÇ£</em><strong><em>CANTUGAS CRITICAL HABITAT FOR Rafflesia mixta AND OTHER THREATENED WILDLIFE SPECIESΓÇ¥</em></strong></p><p><strong>SECTION 1. Basic Policy. </strong>It is the policy of the State to conserve the countryΓÇÖs wildlife resources and their habitats for ecological and economic sustainability. As such, all habitats outside protected areas under RA No. 7586 or the ΓÇ£National Integrated Protected Areas Systems Act), where threatened species are found shall be designated as critical habitat. It is also the policy of the state that all designated critical habitats shall be protected and managed in coordination with the local government units (LGUs) and other concerned groups, from any form of exploitation or destruction which may be detrimental to the survival of the threatened species dependent therein.</p><p><strong>SECTION 2. Objectives. </strong>The objectives of this Order are as follows:</p><p>2.1\tTo provide a legal framework for the protection of the <strong>159.73 hectares</strong> of forestland from destructive resource uses and other types of land use in Barangay Cantugas in the Municipality of Mainit, Province of Surigao del Norte that supports the existence of the <em>Rafflesia mixta</em>, its host plant, and other threatened wildlife species;</p><p>2.2\tTo establish a locally-driven ecosystem management approach that guarantees the dynamic and full participation of LGUs, Indigenous People (IP) communities, peoplesΓÇÖ organizations and other stakeholders integrating threatened species conservation as part of local development planning process and way of life of the people; and</p><p>2.3\tTo sustainably manage the area as a viable habitat for endemic and threatened species; to maintain ecological services and other biodiversity and cultural values; and, potentially for ecotourism development activities, e.g., bird watching, hiking, trekking and camping, that would contribute to inclusive socio-economic growth.</p><p><strong>SECTION 3. Scope and Coverage. </strong>The Cantugas Critical Habitat covers an approximate area of <strong>One Hundred Fifty Nine and 73/100 (159.73) hectares</strong> as indicated on the herein attached area map (<strong>Annex ΓÇ£AΓÇ¥</strong>) which forms an integral part of this Order, <s>subject to private rights if there be any,</s> and to ground survey and delineation, which is particularly described as follows:</p><p>Beginning at a point marked ΓÇ£1ΓÇ¥ on the map, being N 71┬░41ΓÇÖ30ΓÇ¥ W, 2109.237 meters from PRS92 control monument SRN-3246 with geographic coordinates 125┬░28ΓÇÖ19.63831ΓÇ¥ E, 9┬░34ΓÇÖ45.75739ΓÇ¥N located at Barangay Cantugas, Mainit, Surigao del Norte.</p><table><tbody><tr><td><p><strong>Line</strong></p></td><td><p><strong>Bearing</strong></p></td><td><p><strong>Distance (meters)</strong></p></td></tr><tr><td><p>1-2</p></td><td><p>S 4┬░57ΓÇÖ40ΓÇ¥ E</p></td><td><p>1255.487</p></td></tr><tr><td><p>2-3</p></td><td><p>S 52┬░20ΓÇÖ42ΓÇ¥ W</p></td><td><p>351.285</p></td></tr><tr><td><p>3-4</p></td><td><p>N 86┬░21ΓÇÖ4ΓÇ¥ W</p></td><td><p>577.41</p></td></tr><tr><td><p>4-5</p></td><td><p>N 6┬░18ΓÇÖ51ΓÇ¥ W</p></td><td><p>359.833</p></td></tr><tr><td><p>5-6</p></td><td><p>N 1┬░35ΓÇÖ23ΓÇ¥ W</p></td><td><p>80.545</p></td></tr><tr><td><p>6-7</p></td><td><p>N 8┬░46ΓÇÖ13ΓÇ¥ W</p></td><td><p>119.685</p></td></tr><tr><td><p>7-8</p></td><td><p>N 9┬░11ΓÇÖ22ΓÇ¥ W</p></td><td><p>102.197</p></td></tr><tr><td><p>8-9</p></td><td><p>N 1┬░30ΓÇÖ33ΓÇ¥ W</p></td><td><p>122.422</p></td></tr><tr><td><p>9-10</p></td><td><p>N 6┬░0ΓÇÖ35ΓÇ¥ W</p></td><td><p>218.844</p></td></tr><tr><td><p>10-11</p></td><td><p>N 7┬░31ΓÇÖ21ΓÇ¥ W</p></td><td><p>169.256</p></td></tr><tr><td><p>11-12</p></td><td><p>N 5┬░26ΓÇÖ55ΓÇ¥ W</p></td><td><p>298.174</p></td></tr><tr><td><p>12-13</p></td><td><p>N 23┬░33ΓÇÖ20ΓÇ¥ E</p></td><td><p>292.1</p></td></tr><tr><td><p>13-14</p></td><td><p>N 42┬░17ΓÇÖ25ΓÇ¥ E</p></td><td><p>216.041</p></td></tr><tr><td><p>14-15</p></td><td><p>N 89┬░51ΓÇÖ20ΓÇ¥ E</p></td><td><p>9295.656</p></td></tr><tr><td><p>15-16</p></td><td><p>S 80┬░53ΓÇÖ35ΓÇ¥ E</p></td><td><p>278.204</p></td></tr><tr><td><p>16-1</p></td><td><p>S 9┬░1ΓÇÖ22ΓÇ¥ E</p></td><td><p>422.865</p></td></tr><tr><td colspan="2"><p><strong>Total AREA</strong></p></td><td><p><strong>159.73 hectares</strong></p></td></tr></tbody></table><p>Bearings and Distances of lines were derived using the PRS 1992 UTM Zone</p><p>51N coordinate system, subject to actual ground demarcation.</p><p>The DENR-CARAGA in coordination with the Biodiversity Management Bureau (BMB) and National Mapping and Resource Information Authority (NAMRIA) as necessary, shall undertake ground verification of the above-said coordinates within ninety (90) days from the effectivity of this Order.  Natural topographic features of the area, vegetative cover or permanent markers shall be used as boundary monuments/indicators. In case there are rectifications on the technical descriptions of the area, the final map as verified by the composite team of the NAMRIA, DENR-CARAGA and BMB shall be endorsed by the Regional Executive Director and the BMB Director to the DENR Secretary for approval.</p><p><strong>SECTION 4. Management of the Cantugas Critical Habitat for <em>Rafflesia mixta </em>and other threatened wildlife species. </strong>The Cantugas Critical Habitat for <em>Rafflesia mixta </em>and other threatened wildlife species shall be managed by DENR CARAGA, in partnership with the LGU of Mainit, Surigao del Norte and the IPC. The DENR through the Regional Executive Director shall enter into a Memorandum of Agreement (MOA) with the cooperating parties/partners. Alternatively, the concerned Regional Executive Director may delegate the management of the critical habitat to LGU-Mainit and/or the IP through a similar instrument.</p><p>The DENR-CARAGA and its partner/s shall:</p><ul><li><ol><li>Ensure that existing ecosystems in the critical habitat are preserved and are kept in a condition that will support and enhance the existing populations of the <em>Rafflesia mixta, </em>its host plant, and associated naturally occurring flora and fauna;</li><li>Ensure that developmental activities within or in the periphery of the critical habitat undergo the necessary assessment processes so as to safeguard the ecological integrity of the area;</li><li>Ensure the enforcement of applicable environmental laws and all prohibited acts within critical habitat as provided under Section 7 of this Order; </li><li>Ensure that all income from the operation and management of the critical habitat shall be used for the conservation and protection of the area; and,</li><li>Monitor and evaluate compliance of the Critical Habitat Management Plan (CHMP). </li></ol></li></ul><p><strong>SECTION 5. Critical Habitat Management Plan. </strong>The DENR CARAGA, in partnership with the LGU of Mainit, Surigao del Norte and the IP Community, in coordination and collaboration with other local stakeholders, shall jointly prepare and cause the implementation of the CHMP within ninety (90) days upon effectivity of this Order. The CHMP shall be approved by the Regional Executive Director. </p><p>The CHMP must be able to address: a) management objectives; b) key management issues; c) site management strategies and activities such as but not limited to habitat protection, rehabilitation, community organizing, promotion of environmental education and awareness, ecotourism, and other developmental   activities towards the sustainable management of the area; d) translocations; e) administration; f) climate change; g) gender lens; and, h) monitoring and evaluation, among others.  The CHMP must also address the targets, issues and concerns of the National Action Plan on Ecosystems Restoration and Species Extinction Prevention (NAPERSEP), the Philippine Plant Conservation Strategy and Action Plan, and the Ancestral Domain Sustainable Development Protection Plan (ADSDPP).</p><p>For this purpose, the template of the CHMP (BMB Technical Bulletin No. 2017-15) is attached as ΓÇ£<strong>Annex B</strong>ΓÇ¥.  The DENR CARAGA shall submit to BMB a copy of the approved CHMP for record and monitoring purposes.</p><p>In the event that the DENR Regional Executive Director opts to delegate the management of the critical habitat to LGU-Mainit, Surigao del Norte, the regional office shall ensure provision of necessary technical assistance to said LGU and set schemes to monitor and evaluate the implementation of the CHMP, in collaboration with other stakeholders. The DENR through the Regional Executive Director concerned may enter into a Memorandum of Agreement (MOA)/Partnership Agreement with the concerned LGU for the management of the critical habitat.</p><p>The DENR-CARAGA shall review and update the CHMP every five (5) years in consultation with other stakeholders.  </p><p><strong>SECTION 6. Monitoring and Evaluation. </strong>The DENR-CARAGA through the PENRO/CENRO shall undertake monitoring and evaluation on the management of Cantugas Critical Habitat, as well as the implementation of its CHMP.  The DENR-CARAGA shall submit an annual report to the Supervising Undersecretary for Biodiversity and the BMB for integration in the Information Management System of the Bureau. </p><p>The CENRO shall:  </p><ul><li><ol><li>Oversee regular monitoring and enforcement activities within the critical habitat;</li><li>Gather data on habitat conditions, wildlife populations, and human  activities, and submits reports to CENRO;</li><li>Facilitates community participation in conservation efforts and provides education on habitat importance;</li><li>Conducts regular patrols to prevent illegal activities within the critical  Habitat; </li><li>Work closely with LGU-Mainit to integrate local plans and policies; and</li><li>Submit reports to the Regional Executive Director thru proper channel.</li></ol></li></ul><p>The PENRO shall:</p><ul><li><ol><li>Provide technical guidance and oversight to CENRO and LGU-Mainit;</li><li>Train CENRO and LGU personnel on conservation management; and</li><li>Assess CENRO's performance, ensuring compliance with regulations.</li></ol></li></ul><p><strong>SECTION 7. Prohibited Acts and Penalties. </strong>The conduct of the<strong> </strong>following activities inside the Cantugas Critical Habitat are prohibited and punishable in accordance with Sections 27 and 28 of RA 9147:</p><table><tbody><tr><td><p><strong>Illegal Acts</strong></p></td><td><p><strong>Punishment</strong></p></td></tr><tr><td><ol><li>killing and destroying wildlife species, except in the following instances;</li><li>when it is done as part of the religious rituals of established tribal groups or indigenous cultural communities;</li></ol><p>(ii) when the wildlife is afflicted with an incurable communicable disease;</p><p>(iii) when it is deemed necessary to put an end to the misery suffered by the wildlife.</p><p>(iv) when it is done to prevent an imminent danger to the life or limb of a human being; and</p><p>(v) when the wildlife is killed or destroyed after it has been used in authorized research or experiments.</p></td><td><ul><li><ol><li>imprisonment of a minimum of six (6) years and one (1) day to twelve (12) years and/ or a fine of One Hundred Thousand pesos (P100,000.00) to One Million pesos (P1,000,000.00), if inflicted or undertaken against species listed as critical;</li><li>imprisonment of four (4) years and one (1) day to six (6) years and/or a fine of Fifty Thousand Pesos (P50,000.00) to Five Hundred Thousand pesos(P500,000,00), if inflicted or undertaken against endangered species.</li><li>imprisonment of two (2) years and one (1) day to four (4) years and/ or a fine of Thirty Thousand pesos (P30,000.00) to Three Hundred Thousand pesos (P300,000.00), if inflicted or undertaken against vulnerable species;</li><li>imprisonment of one (1) year and one (1) day to two (2) years and /or a fine of Twenty Thousand pesos (P20,000.00) to Two Hundred Thousand pesos (P200,000.00), if inflicted or undertaken against other threatened species; and</li><li>imprisonment of six (6) months and one (1) day to one (1) year and/or a fine of Ten Thousand pesos (P10,000.00) to One Hundred Thousand pesos (P100,000.00), if inflicted or undertaken against other wildlife species.</li></ol></li></ul></td></tr><tr><td><ol><li>inflicting injury which cripples and/or impairs the reproductive system of wildlife species;</li></ol></td><td><ol><li>imprisonment of a minimum of four (4) years and one (1) day to six (6) years and/or a fine of Fifty Thousand pesos P(50,000.00) to Five Hundred Thousand pesos (P500,000.00), if inflicted or undertaken against species listed as critical;</li><li>imprisonment of two (2) years and one (1) day to four (4) years and/ or a fine of Thirty Thousand pesos (P30,000.00) to Two Hundred Thousand pesos (P200,000.00), if inflicted or undertaken against endangered species;</li><li>imprisonment of one (1) year and one (1) day to two (2) years and/or a fine of Twenty Thousand pesos (P20,000.00) to Two Hundred Thousand pesos (P200,000.00), if inflicted or undertaken against vulnerable species;</li><li>imprisonment of six (6) months and one (1) day to one (1) year and/or a fine of Ten Thousand pesos (P10,000.00) to Fifty Thousand pesos (P50,000.00), if inflicted or undertaken against other threatened species; and</li><li>imprisonment of one (1) month to six months (6) and/or a fine of Five Thousand pesos (P5,000.00) to Twenty Thousand pesos (P20,000.00), if inflicted or undertaken against other wildlife species.</li></ol></td></tr><tr><td><ol><li>effecting any of the following acts in critical habitat(s):</li><li>dumping of waste products detrimental to wildlife;</li><li>squatting or otherwise occupying any portion of the critical habitat;</li><li>  mineral exploration and/or</li></ol><p>extraction;</p><ol><li>burning;</li><li>logging; and</li><li>quarrying;</li></ol></td><td rowspan="2"><p>An imprisonment of one (1) month to eight (8) years and/or a fine of Five Thousand pesos (P5,000.00) to Five Million pesos (P5,000,000.00) shall be imposed.</p></td></tr><tr><td><ol><li>introduction, reintroduction, or restocking of wildlife resources;</li></ol></td></tr><tr><td><ol><li>trading of wildlife;</li></ol></td><td><ul><li><ol><li>imprisonment of two (2) years and one (1) day to four (4) years and/ or a fine of Five Thousand pesos (P5,000.00) to Three Hundred Thousand pesos (P300,000.00), if inflicted or undertaken against species listed as critical;</li><li>imprisonment of one (1) year and one (1) day to two (2) years and/or a fine of Two Thousand pesos (P2,000.00) to Two Hundred Thousand pesos (P200,000.00), if inflicted or undertaken against endangered species;</li><li>imprisonment of six (6) months and one (1) day to one (1) year and/or a fine of One Thousand pesos (P1,000.00) to One Hundred Thousand pesos (P100,000.00), if inflicted or undertaken against vulnerable species;</li><li>imprisonment of one (1) month and one (1) day to six months (6) and/or a fine of Five Hundred pesos (P500.00) to Fifty Thousand pesos (P50,000.00), if inflicted or undertaken against species listed as other threatened species; and</li><li>imprisonment of ten (10) days to one (1) month and/or a fine of Two Hundred pesos (P200.00) to Twenty Thousand pesos (P20,000.00), if inflicted or undertaken against other wildlife species.</li></ol></li></ul></td></tr><tr><td><ul><li><ol><li>collecting, hunting, or possessing wildlife, their by-products and derivatives;</li></ol></li></ul></td><td rowspan="2"><ol><li>imprisonment of two (2) years and one (1) day to four (4) years and a fine of Thirty Thousand pesos (P30,000.00) to Three Hundred Thousand pesos (P300,000.00), if inflicted or undertaken against species listed as critical;</li><li>imprisonment of one (1) year and one (1) day to two (2) years and a fine of Twenty Thousand pesos (P20,000.00) to Two Hundred Thousand pesos (P200,000.00), if inflicted or undertaken against endangered species;</li><li>imprisonment of six (6) months and one (1) day to one (1) year and a fine of Ten Thousand pesos (P10,000.00) to One Hundred Thousand pesos (P100,000.00), if inflicted or undertaken against vulnerable species;</li><li>imprisonment of one (1) month and one (1) day to six (6) months and a fine of Five Thousand pesos (P5,000.00) to Fifty Thousand pesos (P50,000.00), if inflicted or undertaken against species listed as other threatened species; and</li><li>imprisonment of ten (10) days to one (1) month and a fine of One Thousand pesos (P1,000.00) to Five Thousand pesos (P5,000.00), if inflicted or undertaken against other wildlife species: <em>Provided, </em>That in case of paragraph (f), where the acts were perpetuated through the means of inappropriate techniques and devices, the maximum penalty herein provided shall be imposed.</li></ol></td></tr><tr><td><ul><li><ol><li>gathering or destroying of active nests, nest trees, host plants and the like;</li></ol></li></ul></td></tr><tr><td><ul><li><ol><li>maltreating and/or inflicting other injuries not covered by the preceding paragraph; and,</li></ol></li></ul></td><td rowspan="2"><ol><li>imprisonment of six (6) months and one (1) day to one (1) year and a fine of Fifty Thousand pesos (P50,000.00) to One Hundred Thousand pesos (P100,000.00), if inflicted or undertaken against species listed as critical species;</li><li>imprisonment of three (3) months and one (1) day to six (6) months and a fine of Twenty Thousand pesos (P20,000.00) to Fifty Thousand pesos (P50,000.00), if inflicted or undertaken against endangered species;</li><li>imprisonment of one (1) month and one (1) day to three (3) months and a fine of Five Thousand pesos (P5,000.00) to Twenty Thousand pesos (P20,000.00), if inflicted or undertaken against vulnerable species;</li><li>imprisonment of ten (10) days to one (1) month and a fine of One Thousand pesos (P1,000.00) to Five Thousand pesos (P5,000.00), if inflicted or undertaken against species listed as other threatened species;</li><li>imprisonment of five (5) days to ten (10) days and a fine of Two Hundred pesos (P200.00) to One Thousand pesos (P1,000.00), if inflicted or undertaken against other wildlife species.</li></ol></td></tr><tr><td><ul><li><ol><li>transporting of wildlife</li></ol></li></ul></td></tr></tbody></table><p><strong>SECTION 8. Funding. </strong>The DENR CARAGA Region shall allocate funds for the operation and implementation of the CHMP.  As such, the DENR CARAGA shall include funds for the purpose in their Annual Work and Financial Plan.  The DENR CARAGA shall also endeavor to engage the LGU and other partner/s to provide funds for the management of the Critical Habitat.</p><p><strong>SECTION 9. Separability Clause.</strong> If any provision of this Order shall be held invalid or unconstitutional, the other portions or provisions hereof which are not affected shall continue in full force and effect. </p><p><strong>SECTION 10. Repealing Clause.</strong> All Orders and other similar issuances inconsistent herewith are hereby revoked, amended, or modified accordingly.</p><p><strong>SECTION 11. Effectivity.</strong> This Order shall take effect fifteen (15) days after its publication in a newspaper of general circulation and upon filing of three (3) certified copies hereof with the Office of the National Administrative Register (ONAR) and the University of the Philippines (UP) Law Center.</p><p><strong>                                                             ATTY. JUAN MIGUEL T. CUNA, CESO I</strong></p><p>  Secretary</p>
HTML;

        $options207 = json_encode([
            'template' => $htmlTemplate,
            'log_history' => true,
            'require_review' => true,
        ]);

        $moduleFields = [
            [
                'id' => 196,
                'module_id' => 1,
                'name' => 'Title',
                'description' => null,
                'sort_order' => 0,
                'show_in_index' => 1,
                'col_span' => 2,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'title',
                'type' => 'text',
                'is_required' => 0,
                'options_json' => null,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 197,
                'module_id' => 1,
                'name' => 'Proposal Summary',
                'description' => null,
                'sort_order' => 1,
                'show_in_index' => 0,
                'col_span' => 2,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'proposal_summary',
                'type' => 'textarea',
                'is_required' => 0,
                'options_json' => null,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 198,
                'module_id' => 1,
                'name' => 'Proponent',
                'description' => null,
                'sort_order' => 2,
                'show_in_index' => 1,
                'col_span' => 1,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'proponent',
                'type' => 'select',
                'is_required' => 0,
                'options_json' => json_encode(["BPKMD", "WRD", "NPD", "CAWED", "CMD", "AFU"]),
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 199,
                'module_id' => 1,
                'name' => 'Policy Type',
                'description' => null,
                'sort_order' => 3,
                'show_in_index' => 1,
                'col_span' => 1,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'policy_type',
                'type' => 'select',
                'is_required' => 0,
                'options_json' => json_encode(["DENR Administrative Order", "Joint Administrative Order", "Memorandum Circular"]),
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 200,
                'module_id' => 1,
                'name' => 'Draft Policy Proposal',
                'description' => null,
                'sort_order' => 4,
                'show_in_index' => 0,
                'col_span' => 1,
                'versioning' => 1,
                'visibility_conditions' => null,
                'slug' => 'draft_policy_proposal',
                'type' => 'attachment',
                'is_required' => 0,
                'options_json' => null,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 201,
                'module_id' => 1,
                'name' => 'Annexes',
                'description' => "Attach here the annexes if there's any",
                'sort_order' => 5,
                'show_in_index' => 0,
                'col_span' => 1,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'annexes',
                'type' => 'attachment',
                'is_required' => 0,
                'options_json' => null,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 202,
                'module_id' => 1,
                'name' => 'CSW',
                'description' => '',
                'sort_order' => 6,
                'show_in_index' => 0,
                'col_span' => 1,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'csw',
                'type' => 'attachment',
                'is_required' => 0,
                'options_json' => null,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 203,
                'module_id' => 1,
                'name' => 'Policy Analysis',
                'description' => '',
                'sort_order' => 7,
                'show_in_index' => 0,
                'col_span' => 1,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'policy_analysis',
                'type' => 'attachment',
                'is_required' => 0,
                'options_json' => null,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 204,
                'module_id' => 1,
                'name' => "Copy of Stakeholder's Consultations",
                'description' => '',
                'sort_order' => 8,
                'show_in_index' => 0,
                'col_span' => 1,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'copy_of_stakeholders_consultations',
                'type' => 'attachment',
                'is_required' => 0,
                'options_json' => null,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 205,
                'module_id' => 1,
                'name' => 'Copy of Resolutions',
                'description' => '',
                'sort_order' => 9,
                'show_in_index' => 0,
                'col_span' => 1,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'copy_of_resolutions',
                'type' => 'attachment',
                'is_required' => 0,
                'options_json' => null,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 206,
                'module_id' => 1,
                'name' => 'Concurrence',
                'description' => '',
                'sort_order' => 10,
                'show_in_index' => 0,
                'col_span' => 1,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'concurrence',
                'type' => 'attachment',
                'is_required' => 0,
                'options_json' => null,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
            [
                'id' => 207,
                'module_id' => 1,
                'name' => 'Draft Policy',
                'description' => '',
                'sort_order' => 11,
                'show_in_index' => 0,
                'col_span' => 2,
                'versioning' => 0,
                'visibility_conditions' => null,
                'slug' => 'draft_policy',
                'type' => 'text_editor',
                'is_required' => 0,
                'options_json' => $options207,
                'created_at' => '2026-06-09 14:32:47',
                'updated_at' => '2026-06-09 14:32:47',
            ],
        ];

        DB::table('module_fields')->insert($moduleFields);
    }
}
