<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WorkflowSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('workflow_stages')->truncate();
        DB::table('workflow_stage_templates')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $workflowStages = [
            [
                'id' => 15,
                'module_id' => 1,
                'name' => 'Initial Document Review',
                'order' => 10,
                'approver_role_id' => 3,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 0,
                'has_return_button' => 1,
                'allow_edit' => 0,
                'default_status' => null,
                'stage_fields_json' => null,
                'notify_on_enter_json' => '[{"type": "specific_email", "value": "webmaster@bmb.gov.ph"}]',
                'date_reminders_json' => null,
                'stage_type' => 'review',
                'auto_advance_days' => null,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => null,
                'created_at' => '2026-06-16 22:53:30',
                'updated_at' => '2026-06-16 22:53:30',
            ],
            [
                'id' => 16,
                'module_id' => 1,
                'name' => 'Review  Draft Policy (Ad Referendum)',
                'order' => 20,
                'approver_role_id' => 4,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 0,
                'has_return_button' => 0,
                'allow_edit' => 0,
                'default_status' => null,
                'stage_fields_json' => null,
                'notify_on_enter_json' => null,
                'date_reminders_json' => null,
                'stage_type' => 'none',
                'auto_advance_days' => 10,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => null,
                'created_at' => '2026-06-16 22:53:30',
                'updated_at' => '2026-06-16 22:53:30',
            ],
            [
                'id' => 17,
                'module_id' => 1,
                'name' => 'Revise Draft Policy',
                'order' => 25,
                'approver_role_id' => 2,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 0,
                'has_return_button' => 0,
                'allow_edit' => 1,
                'default_status' => null,
                'stage_fields_json' => null,
                'notify_on_enter_json' => null,
                'date_reminders_json' => null,
                'stage_type' => 'review',
                'auto_advance_days' => 10,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => null,
                'created_at' => '2026-06-16 22:53:30',
                'updated_at' => '2026-06-16 22:53:30',
            ],
            [
                'id' => 18,
                'module_id' => 1,
                'name' => 'TRC Scheduling',
                'order' => 27,
                'approver_role_id' => 3,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 0,
                'has_return_button' => 0,
                'allow_edit' => 0,
                'default_status' => null,
                'stage_fields_json' => '[{"name": "Date Scheduled", "slug": "date_scheduled", "type": "date", "is_required": true, "options_json": null}]',
                'notify_on_enter_json' => null,
                'date_reminders_json' => '[{"field_slug": "date_scheduled", "recipients": [{"type": "specific_email", "value": "webmaster@bmb.gov.ph"}], "days_before": 1}]',
                'stage_type' => 'review',
                'auto_advance_days' => null,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => null,
                'created_at' => '2026-06-16 22:53:30',
                'updated_at' => '2026-06-16 22:53:30',
            ],
            [
                'id' => 19,
                'module_id' => 1,
                'name' => 'TRC Deliberation',
                'order' => 30,
                'approver_role_id' => 3,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 0,
                'has_return_button' => 0,
                'allow_edit' => 0,
                'default_status' => null,
                'stage_fields_json' => '[{"name": "TRC Minutes of Meeting", "slug": "trc_minutes_of_meeting", "type": "attachment", "is_required": true, "options_json": null}]',
                'notify_on_enter_json' => null,
                'date_reminders_json' => null,
                'stage_type' => 'none',
                'auto_advance_days' => null,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => '[{"label": "Ad referendum", "stage_id": "16"}, {"label": "TRC Scheduling", "stage_id": "18"}, {"label": "PTWG", "stage_id": "20"}]',
                'created_at' => '2026-06-16 22:53:30',
                'updated_at' => '2026-06-16 23:11:21',
            ],
            [
                'id' => 20,
                'module_id' => 1,
                'name' => 'PTWG Endorsement',
                'order' => 36,
                'approver_role_id' => 3,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 0,
                'has_return_button' => 0,
                'allow_edit' => 0,
                'default_status' => null,
                'stage_fields_json' => '[{"name": "Endorsement Letter", "slug": "endorsement_letter", "type": "attachment", "is_required": true, "options_json": null}]',
                'notify_on_enter_json' => null,
                'date_reminders_json' => null,
                'stage_type' => 'review',
                'auto_advance_days' => null,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => null,
                'created_at' => '2026-06-16 22:53:30',
                'updated_at' => '2026-06-16 23:12:13',
            ],
            [
                'id' => 21,
                'module_id' => 1,
                'name' => 'Endorsed (Waiting for PTWG)',
                'order' => 38,
                'approver_role_id' => 5,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 0,
                'has_return_button' => 0,
                'allow_edit' => 0,
                'default_status' => null,
                'stage_fields_json' => '[{"name": "PTWG Return Document", "slug": "ptwg_return_document", "type": "attachment", "is_required": true, "options_json": null}]',
                'notify_on_enter_json' => null,
                'date_reminders_json' => null,
                'stage_type' => 'none',
                'auto_advance_days' => null,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => null,
                'created_at' => '2026-06-16 22:53:30',
                'updated_at' => '2026-06-16 23:16:14',
            ],
            [
                'id' => 22,
                'module_id' => 1,
                'name' => 'Policy Signed and Ready to Upload',
                'order' => 40,
                'approver_role_id' => 3,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 1,
                'has_return_button' => 0,
                'allow_edit' => 0,
                'default_status' => null,
                'stage_fields_json' => '[{"name": "Signed Policy", "slug": "signed_policy", "type": "attachment", "is_required": true, "options_json": null}]',
                'notify_on_enter_json' => null,
                'date_reminders_json' => null,
                'stage_type' => 'approval',
                'auto_advance_days' => null,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => null,
                'created_at' => '2026-06-16 22:53:30',
                'updated_at' => '2026-06-16 22:53:30',
            ],
            [
                'id' => 26,
                'module_id' => 1,
                'name' => 'Consolidate Comments',
                'order' => 26,
                'approver_role_id' => 3,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 0,
                'has_return_button' => 0,
                'allow_edit' => 0,
                'default_status' => null,
                'stage_fields_json' => null,
                'notify_on_enter_json' => null,
                'date_reminders_json' => null,
                'stage_type' => 'none',
                'auto_advance_days' => null,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => '[{"label": "Ad referendum", "stage_id": "16"}, {"label": "TRC Scheduling", "stage_id": "18"}, {"label": "PTWG", "stage_id": "20"}]',
                'created_at' => '2026-06-16 23:07:40',
                'updated_at' => '2026-06-16 23:11:35',
            ],
            [
                'id' => 27,
                'module_id' => 1,
                'name' => 'PTWG to Secretariat',
                'order' => 39,
                'approver_role_id' => 3,
                'reviewer_role_id' => null,
                'requires_all_approvers' => 0,
                'is_final_approval' => 0,
                'has_return_button' => 0,
                'allow_edit' => 0,
                'default_status' => null,
                'stage_fields_json' => null,
                'notify_on_enter_json' => null,
                'date_reminders_json' => null,
                'stage_type' => 'review',
                'auto_advance_days' => null,
                'branch_ad_referendum_stage_id' => null,
                'branch_trc_stage_id' => null,
                'branches_json' => '[{"label": "TRC Scheduling", "stage_id": "18"}]',
                'created_at' => '2026-06-16 23:19:14',
                'updated_at' => '2026-06-16 23:19:14',
            ],
        ];

        // Extracted templates
        $workflowStageTemplates = [
            [
                'id' => 1,
                'name' => 'Policy Proposals — Apr 27, 2026',
                'stages_json' => '[{"name": "Initial Document Review", "order": 10, "allow_edit": false, "stage_type": "review", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": true, "is_final_approval": false, "stage_fields_json": null}, {"name": "Review  Draft Policy (Ad Referendum)", "order": 20, "allow_edit": false, "stage_type": "none", "approver_role": "Reviewer", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null}, {"name": "Revise Draft Policy", "order": 25, "allow_edit": true, "stage_type": "review", "approver_role": "Proponent", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null}, {"name": "TRC Scheduling", "order": 27, "allow_edit": false, "stage_type": "review", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "Date Scheduled", "slug": "date_scheduled", "type": "date", "is_required": true, "options_json": null}]}, {"name": "TRC Deliberation", "order": 30, "allow_edit": false, "stage_type": "none", "approver_role": "TRC Secretariat", "branches_json": [{"label": "Forward to Proponent (For Ad Referendum)", "stage_id": "11"}, {"label": "Forward to Proponent (For Re-Deliberation)", "stage_id": "7"}, {"label": "For PTWG Endorsement", "stage_id": "8"}], "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "TRC Minutes of Meeting", "slug": "trc_minutes_of_meeting", "type": "attachment", "is_required": true, "options_json": null}]}, {"name": "PTWG Endorsement", "order": 36, "allow_edit": false, "stage_type": "review", "approver_role": "Receiving/Releasing", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "Endorsement Letter", "slug": "endorsement_letter", "type": "attachment", "is_required": true, "options_json": null}]}, {"name": "Endorsed (Waiting for PTWG)", "order": 38, "allow_edit": false, "stage_type": "none", "approver_role": "Receiving/Releasing", "branches_json": [{"label": "Forward to Proponent (For Re-Deliberation)", "stage_id": "7"}, {"label": "Proceed to Uploading the Signed Policy", "stage_id": "9"}], "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "PTWG Return Document", "slug": "ptwg_return_document", "type": "attachment", "is_required": true, "options_json": null}]}, {"name": "Policy Signed and Ready to Upload", "order": 40, "allow_edit": false, "stage_type": "approval", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": true, "stage_fields_json": [{"name": "Signed Policy", "slug": "signed_policy", "type": "attachment", "is_required": true, "options_json": null}]}, {"name": "Revise Draft Policy", "order": 42, "allow_edit": true, "stage_type": "review", "approver_role": "Proponent", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null}, {"name": "Ad Referendum (Re-Routed)", "order": 44, "allow_edit": false, "stage_type": "none", "approver_role": "Reviewer", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null}, {"name": "From Ad Referendum (Re-Routed)", "order": 50, "allow_edit": false, "stage_type": "none", "approver_role": "TRC Secretariat", "branches_json": [{"label": "For PTWG Endorsement", "stage_id": "8"}, {"label": "Forward to Proponent (For Ad Referendum)", "stage_id": "11"}, {"label": "Forward to Proponent (For Re-Deliberation)", "stage_id": "7"}], "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null}]',
                'created_at' => '2026-04-27 09:13:07',
                'updated_at' => '2026-04-27 09:13:07',
            ],
            [
                'id' => 2,
                'name' => 'Policy Proposals — May 08, 2026',
                'stages_json' => '[{"name": "Initial Document Review", "order": 10, "allow_edit": false, "stage_type": "review", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": true, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": [{"type": "specific_email", "value": "webmaster@bmb.gov.ph"}]}, {"name": "Review  Draft Policy (Ad Referendum)", "order": 20, "allow_edit": false, "stage_type": "none", "approver_role": "Reviewer", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "Revise Draft Policy", "order": 25, "allow_edit": true, "stage_type": "review", "approver_role": "Proponent", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "TRC Scheduling", "order": 27, "allow_edit": false, "stage_type": "review", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "Date Scheduled", "slug": "date_scheduled", "type": "date", "is_required": true, "options_json": null}], "date_reminders_json": [{"field_slug": "date_scheduled", "recipients": [{"type": "specific_email", "value": "webmaster@bmb.gov.ph"}], "days_before": 1}], "notify_on_enter_json": null}, {"name": "TRC Deliberation", "order": 30, "allow_edit": false, "stage_type": "none", "approver_role": "TRC Secretariat", "branches_json": [{"label": "Forward to Proponent (For Ad Referendum)", "stage_id": "11"}, {"label": "Forward to Proponent (For Re-Deliberation)", "stage_id": "7"}, {"label": "For PTWG Endorsement", "stage_id": "8"}], "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "TRC Minutes of Meeting", "slug": "trc_minutes_of_meeting", "type": "attachment", "is_required": true, "options_json": null}], "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "PTWG Endorsement", "order": 36, "allow_edit": false, "stage_type": "review", "approver_role": "Receiving/Releasing", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "Endorsement Letter", "slug": "endorsement_letter", "type": "attachment", "is_required": true, "options_json": null}], "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "Endorsed (Waiting for PTWG)", "order": 38, "allow_edit": false, "stage_type": "none", "approver_role": "Receiving/Releasing", "branches_json": [{"label": "Forward to Proponent (For Re-Deliberation)", "stage_id": "7"}, {"label": "Proceed to Uploading the Signed Policy", "stage_id": "9"}], "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "PTWG Return Document", "slug": "ptwg_return_document", "type": "attachment", "is_required": true, "options_json": null}], "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "Policy Signed and Ready to Upload", "order": 40, "allow_edit": false, "stage_type": "approval", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": true, "stage_fields_json": [{"name": "Signed Policy", "slug": "signed_policy", "type": "attachment", "is_required": true, "options_json": null}], "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "Revise Draft Policy", "order": 42, "allow_edit": true, "stage_type": "review", "approver_role": "Proponent", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "Ad Referendum (Re-Routed)", "order": 44, "allow_edit": false, "stage_type": "none", "approver_role": "Reviewer", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "From Ad Referendum (Re-Routed)", "order": 50, "allow_edit": false, "stage_type": "none", "approver_role": "TRC Secretariat", "branches_json": [{"label": "For PTWG Endorsement", "stage_id": "8"}, {"label": "Forward to Proponent (For Ad Referendum)", "stage_id": "11"}, {"label": "Forward to Proponent (For Re-Deliberation)", "stage_id": "7"}], "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": null}]',
                'created_at' => '2026-05-08 13:56:10',
                'updated_at' => '2026-05-08 13:56:10',
            ],
            [
                'id' => 4,
                'name' => 'Policy Proposals — Jun 16, 2026',
                'stages_json' => '[{"name": "Initial Document Review", "order": 10, "allow_edit": false, "stage_type": "review", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": true, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": [{"type": "specific_email", "value": "webmaster@bmb.gov.ph"}]}, {"name": "Review  Draft Policy (Ad Referendum)", "order": 20, "allow_edit": false, "stage_type": "none", "approver_role": "Reviewer", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "Revise Draft Policy", "order": 25, "allow_edit": true, "stage_type": "review", "approver_role": "Proponent", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": 10, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "Consolidate Comments", "order": 26, "allow_edit": false, "stage_type": "none", "approver_role": "TRC Secretariat", "branches_json": [{"label": "Ad referendum", "stage_id": "16"}, {"label": "TRC Scheduling", "stage_id": "18"}, {"label": "PTWG", "stage_id": "20"}], "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "TRC Scheduling", "order": 27, "allow_edit": false, "stage_type": "review", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "Date Scheduled", "slug": "date_scheduled", "type": "date", "is_required": true, "options_json": null}], "date_reminders_json": [{"field_slug": "date_scheduled", "recipients": [{"type": "specific_email", "value": "webmaster@bmb.gov.ph"}], "days_before": 1}], "notify_on_enter_json": null}, {"name": "TRC Deliberation", "order": 30, "allow_edit": false, "stage_type": "none", "approver_role": "TRC Secretariat", "branches_json": [{"label": "Ad referendum", "stage_id": "16"}, {"label": "TRC Scheduling", "stage_id": "18"}, {"label": "PTWG", "stage_id": "20"}], "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "TRC Minutes of Meeting", "slug": "trc_minutes_of_meeting", "type": "attachment", "is_required": true, "options_json": null}], "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "PTWG Endorsement", "order": 36, "allow_edit": false, "stage_type": "review", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "Endorsement Letter", "slug": "endorsement_letter", "type": "attachment", "is_required": true, "options_json": null}], "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "Endorsed (Waiting for PTWG)", "order": 38, "allow_edit": false, "stage_type": "none", "approver_role": "Receiving/Releasing", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": [{"name": "PTWG Return Document", "slug": "ptwg_return_document", "type": "attachment", "is_required": true, "options_json": null}], "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "PTWG to Secretariat", "order": 39, "allow_edit": false, "stage_type": "review", "approver_role": "TRC Secretariat", "branches_json": [{"label": "TRC Scheduling", "stage_id": "18"}], "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": false, "stage_fields_json": null, "date_reminders_json": null, "notify_on_enter_json": null}, {"name": "Policy Signed and Ready to Upload", "order": 40, "allow_edit": false, "stage_type": "approval", "approver_role": "TRC Secretariat", "branches_json": null, "reviewer_role": null, "default_status": null, "auto_advance_days": null, "has_return_button": false, "is_final_approval": true, "stage_fields_json": [{"name": "Signed Policy", "slug": "signed_policy", "type": "attachment", "is_required": true, "options_json": null}], "date_reminders_json": null, "notify_on_enter_json": null}]',
                'created_at' => '2026-06-16 23:20:12',
                'updated_at' => '2026-06-16 23:20:12',
            ]
        ];

        DB::table('workflow_stages')->insert($workflowStages);
        DB::table('workflow_stage_templates')->insert($workflowStageTemplates);
    }
}
